### ISSUE TITLE
It Doesn't work！！

### ISSUE THREAD

**Issue by cssxn** [BigNerd95/Chimay-Red#12]
The listener has no react
![image](https://user-images.githubusercontent.com/11917920/35661730-1d2067b6-074f-11e8-8f5b-2a01f1e4744f.png)

**Comment by BigNerd95** [comment]
May be due to different stack size of older versions
I'll test it on 6.37.2 next days

**Comment by BigNerd95** [comment]
Also try make it crash before stack clash
`./POCs/CrashPOC.py 192.168.1.129 dos`

**Comment by cssxn** [comment]
I've tried! but nothing changes. what version have you tested

**Comment by nanolikeyou** [comment]
I meet the same question in 6.27,mips version,no listener and seems no command run
the log is:
Crash...
Connected
Sent
Sent
Opening 2 sockets
Connected
Connected
Stack clash...
Sent
Sent
Sent
Sending payload
Error sending data

**Comment by beeterman** [comment]
I am also 
Sending payload
Error sending data
**on 6.37.3 mipsbe**

**Comment by BigNerd95** [comment]
Just tried on 6.37.3 x86 and it is working for me

**Comment by BigNerd95** [comment]
Same on 6.37.2, for me it is working
