### ISSUE TITLE
Stack Clash x86 fixes for old versions

### ISSUE THREAD

**Issue by Hume0x** [BigNerd95/Chimay-Red#21]
Hi BigNerd, you have planned, to make compatible the StackClash_x86 script for old versions ?, I was observing that the source code differs a lot between the new and old versions of ROS.
Is possible to obtain the stack size directly from the binary file of the old versions or should I calculate it in the runtime, how could I get it without using IDA, any idea?, 
I'm not very familiar with IDA and remote gdb debugging.

![6 32 2](https://user-images.githubusercontent.com/11588112/36068688-b1465038-0eb9-11e8-95d4-878052f38dd2.png)
![6 38 4](https://user-images.githubusercontent.com/11588112/36068706-961cb706-0eba-11e8-946d-a6608e316dfb.png)

I've seen a good article that talks about this, based on your work.

[https://xianzhi.aliyun.com/forum/topic/1908](url)

Thank you for your time

**Comment by BigNerd95** [comment]
It's easy to update
Tomorrow i'll update it

**Comment by BigNerd95** [comment]
updated

**Comment by Hume0x** [comment]
really cool, now working fine!
