### ISSUE TITLE
extract_user.py index out of range

### ISSUE THREAD

**Issue by Hume0x** [BigNerd95/Chimay-Red#23]
Hi,
in some lines the index is out of range, but adding an exception control works perfectly
[extract_user.py#L10](https://github.com/BigNerd95/Chimay-Red/blob/c181f50c8003d9b42c539b483ca3b8967d60af49/tools/extract_user.py#L10)
`try:
            passw += chr(pass_enc[i] ^ key[i])
        except:
            continue`

**Comment by BigNerd95** [comment]
Can you send me a user.dat that cause this problem?
If it is private send it to my email address

**Comment by Hume0x** [comment]
Sorry, i do not think it is possible, it contains very sensitive information, where the name of the objective is exposed

**Comment by BigNerd95** [comment]
Fixed:
[https://github.com/BigNerd95/Chimay-Red/commit/5ed609ec4989dd7a0509bc162def3b2cc4a8eedb](url)
