### ISSUE TITLE
Cannot get the www_binary

### ISSUE THREAD

**Issue by SrSands** [BigNerd95/Chimay-Red#33]
I have an vmware running routerOS 6.35.4, I can ping it and access it from my browser but i can't get the first command to work. I don't know if i have to teak some setting in the virtual machine or simply that I am a total noob. Here is the output of the command line:

`./tools/getROSbin.py 6.35.4 x86 /nova/bin/www www_binary`
Traceback (most recent call last):
  File "./tools/getROSbin.py", line 5, in <module>
    import requests, sys, io, PySquashfsImage
ImportError: No module named 'PySquashfsImage'

thanks

**Comment by BigNerd95** [comment]
http://lmgtfy.com/?q=ImportError%3A+No+module+named
