### ISSUE TITLE
Cann't excute system command.

### ISSUE THREAD

**Issue by Gczaizi** [BigNerd95/Chimay-Red#37]
I test the script in VMware enviroment with version 6.36.3/6.38.4/6.37.1/6.35.4 routerOS(x86). And it worked. 
But when I test it in the real Internet, I got a response like this:

2566697930 690793 roteros.dll 6.37.1
136152226 36609 advtool.dll 6.37.1
1932145938 46725 ipv6.dll 6.37.1
487958804 44697 mpls.dll 6.37.1
2878013794 48741 ppp.dll 6.37.1
2401832776 60832 roting4.dll 6.37.1
2460574432 49413 secure.dll 6.37.1
1547061561 2542 system.dll 6.37.1

Can anyone tell me the reason?

**Comment by BigNerd95** [comment]
Maybe the board is not x86

**Comment by agpsi** [comment]
This means you're downloading Winbox's libraries. It happens when you access the router/system with a specific version for the first time. After that, libraries will be cached and it won't happen anymore.

**Comment by Gczaizi** [comment]
Thanks!
