### ISSUE TITLE
KeyError: 'strncpy'

### ISSUE THREAD

**Issue by joancefet** [BigNerd95/Chimay-Red#39]
![image](https://user-images.githubusercontent.com/669549/38701585-a88a5364-3e74-11e8-8238-e78bad63e0b8.png)

**Comment by Hume3** [comment]
only works in python 2

**Comment by BigNerd95** [comment]
I dont know why everybody prefix the script with python2 or python3.
Where in my examples i used it?

**Comment by joancefet** [comment]
Ow sorry, I thought it worked in python 3, because I had errors in python 2.7

> I dont know why everybody prefix the script with python2 or python3.

I have both versions.

**Comment by BigNerd95** [comment]
My scripts automatically select the right version
You dont have to specify it

**Comment by joancefet** [comment]
Ok, thanks, solved.
