### ISSUE TITLE
upload a busybox on x86,but it can not work

### ISSUE THREAD

**Issue by lhlsec** [BigNerd95/Chimay-Red#48]
Hi,

I uploaded a busybox(on x86 arch) using the method you provided, 
![image](https://user-images.githubusercontent.com/12195350/40593637-5c595808-625c-11e8-96a6-dae8b2d11ea2.png)

but it can't be executed,I don't know why it can't be executed.Did you succeed under the x86 architecture?And can you perform under mips?

                       Regards，
                       Xigua

**Comment by BigNerd95** [comment]
It is working on both mipsbe and x86 for me

**Comment by lhlsec** [comment]
Strangely, I tried it on the version 6.30.4（both x86 and mipsbe）,and they didn't work. Anyway, thank you very much.
