### ISSUE TITLE
MIPS Equivalent

### ISSUE THREAD

**Issue by MoJo1760** [BigNerd95/Chimay-Red#7]
Do you have any insight to the MIPS equivalent ROP Chain (registers / opcodes ?)  Or even how to detect the running target as mips vs x86.

**Comment by BigNerd95** [comment]
I will release the MIPS version as soon it is ready.
To detect the architecture I didn't find any method through "www" (http).
The only way (for now) is using MNDP (Mikrotik Neighbor Discovery Protocol) or LLDP.
But using these methods the detection can happen only on LAN (not via internet).

**Comment by moj0-bf** [comment]
SNMP public is on by default as well - which might yield some information
